<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <h1 class="text-primary">LogIn Form</h1>
    <div class="row">
        <div class="col-md-12">
            <?php if (!empty($errors)):?>
            <div class="alert alert-danger" role="alert">
               <?php $errorOutput = implode('<br>', $errors); echo $errorOutput; ?>
            </div>
            <?php endif; ?>
            <?php
            if(isset($_POST) && $_SERVER["REQUEST_METHOD"] == "POST" && empty($errors)) {
                print_r(nl2br($newFile));
            }
            ?>
        </div>
    </div>
    <br>
    <form class="form-horizontal" role="form" action="index.php" method="POST">
        <div class="form-group row">
            <div class="col">
                <label for="username">Enter your name</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Name">
            </div>
        </div>
        <div class="form-group row">
            <div class="col">
                <label for="taskNumber">Enter task number</label>
                <input type="text" class="form-control" id="taskNumber" name="taskNumber" placeholder="Task Number">
            </div>
        </div>
        <div class="form-group row">
            <div class="col">
                <label for="months">Enter months</label>
                <input type="text" class="form-control" id="months" name="months" placeholder="Number Of Months">
            </div>
        </div>
        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
</body>
</html>